#!/bin/bash

build=$1
file="build/$build/.build-complete"
script="build-$build"

if [ ! -f "$file" ]; then
	echo "Awaiting build $build..."
	echo "Note: this script assumes you are running $script in parallel!"
	
	while [ ! -f "$file" ]; do
		sleep 1
	done
fi
