#!/bin/bash

if [[ $PLATFORM == "" ]]; then
	echo "await-build: PLATFORM environment variable must be specified"
	exit 1
fi

suffix=""

if [[ $PLATFORM != "test" ]]; then
	suffix="-dev"
fi

build="$PLATFORM$suffix"
file="build/$build/.build-complete"

if [[ $1 == "--clean" ]]; then
	if [ -f "$file" ]; then
		rm "$file"
	fi
else
	if [ ! -f "$file" ]; then
		echo "Awaiting build $build..."
		
		while [ ! -f "$file" ]; do
			sleep 1
		done
	fi
fi
