#!/bin/bash

mode=$1

dir="vendor/public/tree-sitter"

currentJs="$dir/tree-sitter.js"
currentWasm="$dir/tree-sitter.wasm"
dynamicJs="$dir/tree-sitter-dynamic.js"
dynamicWasm="$dir/tree-sitter-dynamic.wasm"
staticJs="$dir/tree-sitter-static.js"
staticWasm="$dir/tree-sitter-static.wasm"

if [ -f $dynamicJs ]; then
	currentMode="static"
else
	currentMode="dynamic"
fi

function setMode {
	if [[ $mode == "dynamic" && $currentMode == "static" ]]; then
		mv $currentJs $staticJs
		mv $currentWasm $staticWasm
		mv $dynamicJs $currentJs
		mv $dynamicWasm $currentWasm
	elif [[ $mode == "static" && $currentMode == "dynamic" ]]; then
		mv $currentJs $dynamicJs
		mv $currentWasm $dynamicWasm
		mv $staticJs $currentJs
		mv $staticWasm $currentWasm
	fi
}

if [ ! -z $mode ]; then
	setMode
	
	echo "Mode set to $mode"
else 
	echo "Current mode is $currentMode"
fi
